spring:
  profiles:
    active: dev
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: authentication
    hostname: localhost
    instance-id: authentication