server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com:
      netflix:
        discovery: 'OFF'
        eureka: 'OFF'

