spring:
  profiles:
    active: dev
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com:
      netflix:
        discovery: 'OFF'
        eureka: 'OFF'
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: demo
  resource: demo-app
  principal-attribute: preferred_username
